version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: saicafe
      MYSQL_USER: cafeuser
      MYSQL_PASSWORD: cafe123
    volumes:
      - db_data:/var/lib/mysql
      - ./Leafcafe.sql:/docker-entrypoint-initdb.d/Leafcafe.sql:ro

volumes:
  db_data:
